### ISSUE TITLE
asp.net core csproj issue

### ISSUE THREAD

**Issue by rodchenkov** [cchitsiang/nuget-selenium-webdriver-microsoftwebdriver#5]
Hi

Trying to install your package to asp.net core 1.1 csproj and I found that it doesn't copy exe file to bin directory.

Can you please check and solve this.

e.g. this
https://github.com/jsakamoto/nupkg-selenium-webdriver-iedriver
work fine for me

Thank you!

**Comment by cchitsiang** [comment]
Will try to take a look somewhere this week

**Comment by rodchenkov** [comment]
Thank you!

**Comment by jsakamoto** [comment]
@rodchenkov I could not reproduce the bug what you said.

![image](https://cloud.githubusercontent.com/assets/95908/24355424/d084b3d4-1330-11e7-98c8-f345bb01eaf2.png)

Could you show us your project files?

My sample project is here: [WebApplication1.zip](https://github.com/cchitsiang/nuget-selenium-webdriver-microsoftwebdriver/files/872365/WebApplication1.zip)

P.S. I used Visual Studio "2017RTM".

**Comment by rodchenkov** [comment]
Just tested, no success.

![2017-03-27_17-06-53](https://cloud.githubusercontent.com/assets/7562752/24360500/259a0c96-1310-11e7-94b9-df91b2b26af3.png)

**Comment by rodchenkov** [comment]
Maybe problem with install.
In chromedriver nuget package I found this

![2017-03-27_17-11-52](https://cloud.githubusercontent.com/assets/7562752/24360665/a4845cc8-1310-11e7-873c-d191778dc61b.png)
![2017-03-27_17-12-18](https://cloud.githubusercontent.com/assets/7562752/24360664/a47db922-1310-11e7-8b6a-01dd9ddbad57.png)

**Comment by rodchenkov** [comment]
In your package I found this

![2017-03-27_17-13-56](https://cloud.githubusercontent.com/assets/7562752/24360726/d9d0cfd8-1310-11e7-8dff-74b1e07574d5.png)
![2017-03-27_17-14-07](https://cloud.githubusercontent.com/assets/7562752/24360727/d9d24d5e-1310-11e7-9ac4-995c10b28a73.png)

Maybe this is the problem with targets and ps1

**Comment by jsakamoto** [comment]
@rodchenkov Oh, I'm sorry!

I tested with my local package repository and installed from local private NuGet package.

I fixed the problem that .NET Core project was no longer supported PowerShell scripts in NuGet package (see also commit 420e85f07edfc7957199ccfb2b6934d6d9ac2cbc), but it doesn't still release due to NuGet package owner is @cchitsiang  and @rafflesgun, not me.  
(My work completed Nov. 2016, but the time stamp of latest published NuGet package is Oct. 2016)

If you want fix this issue immediately, you can use my latest private Beta version NuGet package from the follow link if you prefer.

https://github.com/jsakamoto/nuget-selenium-webdriver-microsoftwebdriver/releases/tag/v.10.0.14393.1-beta

**Comment by rodchenkov** [comment]
@jsakamoto thank you!

I will wait for Nuget package. Hope it will be ready soon.
Please let me know when it is ready so that I can check it and close issue.

**Comment by rafflesgun** [comment]
@rodchenkov Nuget Package has updated to 10.0.14393.**1**. PowerShell no longer part of the nuget package.
Thank you.

**Comment by rodchenkov** [comment]
@rafflesgun thank you!

Good job!
Just tested and all works!
